config/routes.rb
Rails.application.routes.draw do
 root 'contents#index'
 
 resources :contents
   resources :contents do
  end
  
  resources :comments
  resources :contents do
   member do
    get :comments
    # get '/news', to: 'comments'
   end
  end
  get 'session/new'

 # Navbar
 get '/newcomments' => 'comments#index'
 get '/submit' => 'contents#new'
 get '/about' => 'rad#about'
 get '/signup' => 'users#signup'
 
 # Session
 get    '/login',   to: 'sessions#new'
 post   '/login',   to: 'sessions#create'
 get    '/logout',  to: 'sessions#destroy'
 
 get '/v0/item/c:id' => 'v0#getAPIC', format: true
 get '/v0/item/n:id' => 'v0#getAPIN', format: true
 post '/v0/item/create' => 'v0#postAPI'
 get 'item' => 'v0#items'
 
 resources :users
 
end


app/models/content.rb
class Content < ActiveRecord::Base
    validates :news_title, presence: true,length: { in: 10..200 }
    VALID_URL_REGEX = /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix
    validates :news_source, format: { with:  VALID_URL_REGEX }
    belongs_to :user
    has_many :comment
    
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy, :next]
   before_action :set_page, only: [:index]
  before_filter :require_login, :only=>[:new, :show, :comments]

  # GET /contents
  # GET /contents.json
  def index
    # The news home page will show eight news per page
    @contents = Content.order('created_at DESC').limit(8).offset(@page.to_i * 8)
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to '/', notice: 'Content was successfully created.' }
        format.json { render :show, :created, location: @content , status:200 , message:"OK" }
          
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity , message:"Errors" }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  # GET /contents/1/comments
  def comments
    @content = Content.find(params[:id])
    @comment = @content.comment.order('created_at DESC')
    @comment_in_content = Comment.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:news_title, :news_website, :news_source, :author)
    end

  def set_page
    @page = params[:page]
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
  def current_content
    @current_content ||= Content.find_by(id:[:content_id])
  end
end

app/views/contents/_form.html.erb
<% provide(:title, "Submit A News") %>
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :news_title %><br>
    <%= f.text_area :news_title,:rows=>"7" ,:cols=>"60" ,required: true, placeholder: "(required)"%><br />
  </div>
  <div class="field">
    <!--Link for the news <%= f.text_field :news_website %>-->
  </div>
  <div class="field">
    News source (optional) <%= f.text_field :news_source %>
  </div>
  <div class="field">
    <%= f.hidden_field :author, :value => current_user.name %>
  </div>
  <div class="actions">
    <%= f.submit "Submit"%>
  </div>
<% end %>

app/views/contents/comments.html.erb
<% provide(:title, @content.news_title)%>
<%= @content.news_title %> (<%= @content.news_source %>) <br> 
by <%= link_to @content.author, current_user %> 
   <%= time_ago_in_words(@content.created_at) %> ago|
   <!--<%= link_to @content.comment.count, comments_path  %> comments -->
   <%= @content.comment.count.to_s << " comments" %>
     
<%= form_for(@comment_in_content) do |f| %>
 <div class="field"> 
    <%= f.text_area :comment_title,:rows=>"7" ,:cols=>"60" ,required: true, placeholder: "(required)"%><br />
    <%= f.hidden_field :comment_author, :value => current_user.name %>
    <%= f.hidden_field :content_id, :value => @content.id%>
 </div>
 <div class="actions">
    <%= f.submit 'Add Comment'%>
  </div>
<% end %>
    


<% for comment in @comment do %>
<p>
  <%= comment.comment_author %> <%= time_ago_in_words(comment.created_at) %> ago <br>
  <%= comment.comment_title %>
</p>
<% end %>


app/views/contents/edit.html.erb
<h1>Editing Content</h1>
<%= form_for(@content) do |f| %>
<!--<%= render 'form' %>-->
<%= @content.news_title%> (<%= @content.news_source %>)<br>
         by <%=@content.author%> |
        <%= time_ago_in_words(@content.created_at) %> ago|
        <%= link_to @content.comment.count, comments_content_path(@content)  %> comments <br><br>
 <br><%= f.text_area :comment,:rows=>"7" ,:cols=>"60" ,required: true, placeholder: "(test)"%><br />
  

    <%= f.submit "Submit"%>
<% end %>
<br><br>
  <%= @content.author %>
  <%= time_ago_in_words(@content.created_at) %> ago<br><br>
  


<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<% provide(:title, "Home Page #" << @page.to_s) %>
<!--<p id="notice"><%= notice %></p>-->

<h1>RMIT News</h1>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <%= link_to content.news_title , content.news_source %> <br>
         by <%= link_to content.author, current_user%> |
              <%= time_ago_in_words(content.created_at) %> ago|
        <%= link_to content.comment.count.to_s << ' comments', '/item?id=' << content.id.to_s %>
        <br><br>
       
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Load more', root_path(page: @page.to_i + 1), class: "btn btn-info"%>
<br>

<%= link_to 'New Content', new_content_path %>


app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form' %>

<!--<%= link_to 'Back', contents_path %>-->

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>News title:</strong>
  <%= @content.news_title %>
</p>

<p>
  <strong>News source:</strong>
  <%= @content.news_source %>
</p>

<p>
  <strong>Author:</strong>
  <%= @content.author %>
</p>

<p>
  <strong>Total comments:</strong>
  <%= @content.comment.count %>
</p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>