config/routes.rb
Rails.application.routes.draw do
 root 'contents#index'
 
 resources :contents
   resources :contents do
  end
  
  resources :comments
  resources :contents do
   member do
    get :comments
    # get '/news', to: 'comments'
   end
  end
  get 'session/new'

 # Navbar
 get '/newcomments' => 'comments#index'
 get '/submit' => 'contents#new'
 get '/about' => 'rad#about'
 get '/signup' => 'users#signup'
 
 # Session
 get    '/login',   to: 'sessions#new'
 post   '/login',   to: 'sessions#create'
 get    '/logout',  to: 'sessions#destroy'
 
 get '/v0/item/c:id' => 'v0#getAPIC', format: true
 get '/v0/item/n:id' => 'v0#getAPIN', format: true
 post '/v0/item/create' => 'v0#postAPI'
 get 'item' => 'v0#items'
 
 resources :users
 
end


app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :content
 
    validates :comment_title, presence: true, length: { in: 3...1000 }
    # validates_length_of :comment_title, :minimum => 3
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_filter :require_login, only: [:new]

  # GET /comments
  # GET /comments.json
  def index
    # The New comments page will show and only show three comments sorted by the creation date.
    @comments = Comment.limit(3).order('created_at DESC').all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to '/newcomments', notice: 'Comment was successfully created.' }
        format.json { render :show, :created, location: @comment, status:200 , message:"OK" }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity , message:"Errors"}
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment_title, :content_id, :comment_author)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  
    <%=f.text_area :comment_title,:rows=>"7" ,:cols=>"60" ,required: true%><br>
    <%= f.select :content_id, Content.all.collect {|c| [( c.news_title ), c.id]}%>
    <%= f.hidden_field :comment_author, :value => current_user.name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<% provide(:title, "New comments") %>


<h1>Listing Comments</h1>


    <% @comments.each do |comment| %>
      
        <%= link_to comment.comment_author , current_user%>
          <%= time_ago_in_words(comment.created_at) %> ago|
         on <%= link_to comment.content.news_title, '/item?id=' << comment.content.id.to_s%><br>
        <%= comment.comment_title %><br><br>
    
       
    <% end %>

<br>
<%= link_to 'New comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment title:</strong>
  <%= @comment.comment_title %>
  
</p>

<p>
  <strong>Commented by:</strong>
  <%= @comment.comment_author %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>