config/routes.rb
Rails.application.routes.draw do
 root 'contents#index'
 
 resources :contents
   resources :contents do
  end
  
  resources :comments
  resources :contents do
   member do
    get :comments
    # get '/news', to: 'comments'
   end
  end
  get 'session/new'

 # Navbar
 get '/newcomments' => 'comments#index'
 get '/submit' => 'contents#new'
 get '/about' => 'rad#about'
 get '/signup' => 'users#signup'
 
 # Session
 get    '/login',   to: 'sessions#new'
 post   '/login',   to: 'sessions#create'
 get    '/logout',  to: 'sessions#destroy'
 
 get '/v0/item/c:id' => 'v0#getAPIC', format: true
 get '/v0/item/n:id' => 'v0#getAPIN', format: true
 post '/v0/item/create' => 'v0#postAPI'
 get 'item' => 'v0#items'
 
 resources :users
 
end


app/controllers/rad_controller.rb
class RadController < ApplicationController
  before_filter :require_login, :only=>[:submit,:newcomments]
  def index
  end
  
  def newcomments
  end
  
  def submit
  end
  
  def about
  end
  
  def login
  end

  
end

app/views/rad/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
</head>
<body>
<div class="jumbotron">
    <h1>About</h1>
    <p><h3>Name of group members:</h3><br><br>
    <h4>Bramantha Patra s3549111</h4>
    <h4>St Ee Pon s3525667</h4>
    </p>
</div>
<p>
    Heroku:
</p>
<p>
    <a href="https://bitbucket.org/s3525667/rad18_assign_2_group_-s3525667-_-s3549111/"> Bitbucket URL </a>
</p>
</body>
</html>

app/views/rad/index.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
</head>
<body>
<div class="center jumbotron">
  <h1>RAD Assignment 2</h1><br>
  <h2>@news_title</h2>
  

  
  <button type="button" class="btn btn-outline-secondary btn-lg"><%= link_to "Contents", controller:"contents" , action: "index"%></button>
  

</body>
</html>
<p id="notice"><%= notice %></p>

app/views/rad/login.html.erb
<% provide(:title, "Submit") %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
</head>
<body>
   <p align='center'>
        <div class="modal-dialog">
	<div class="loginmodal-container">
<h3>Log in</h3>

	<div class="row">
	  <div class="col-md-6 col-md-offset-3">
	    <%= form_for(:session, url: login_path) do |f| %>
	
	      <%= f.label :email %>
	      <%= f.email_field :email, class: 'form-control' %>
	
	      <%= f.label :password %>
	      <%= f.password_field :password, class: 'form-control' %>
	
	      <%= f.submit "Log in", class: "btn btn-primary" %>
	    <% end %>
	    
	    <%= form_for(@user) do |f| %>
					
					      <%= f.label :name %>
					      <%= f.text_field :name, class: 'form-control' %>
					
					      <%= f.label :email %>
					      <%= f.email_field :email, class: 'form-control' %>
					
					      <%= f.label :password %>
					      <%= f.password_field :password, class: 'form-control' %>
					
					      <%= f.label :password_confirmation, "Confirmation" %>
					      <%= f.password_field :password_confirmation, class: 'form-control' %>
					
							<br>
					      <%= f.submit "Create my account", class: "btn btn-primary" %>
					    <% end %>
	
	    <!--<p> Don't have an account? <%= link_to "Sign Up Now", controller:"users" , action: "signup"%> </p> -->
	  </div>
	</div>
 
  </div>
				  
	<div class="modal-dialog"></div>
					
</p>
</body>
</html>

app/views/rad/newcomments.html.erb
<% provide(:title, "New comments") %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
</head>
<body>
<h1>About</h1>

  <b>Name:</b>
  <%= @current_user.name %>
</p>
 
<p>
  <b>ID:</b>
  <%= @current_user.id %>
</p><br>

<h2>Add a comment:</h2><br>


</p>
</body>
</html>